// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIaTG2EvX5rMym8BVAzWr8Y43kbkAKuNo',
    appId: '1:100924810151:web:6ce24aaa41fc872c05cc82',
    messagingSenderId: '100924810151',
    projectId: 'imgify-5fd0d',
    authDomain: 'imgify-5fd0d.firebaseapp.com',
    storageBucket: 'imgify-5fd0d.firebasestorage.app',
    measurementId: 'G-NMRD86JE2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv9oWcDegzVhzoxhWrza9nKOZ6-H1tbYk',
    appId: '1:100924810151:android:f72591563e9aa25305cc82',
    messagingSenderId: '100924810151',
    projectId: 'imgify-5fd0d',
    storageBucket: 'imgify-5fd0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa2Su1HS9y6zHb-YL3KAyISkZFugyogRA',
    appId: '1:100924810151:ios:4ac3bf9b0108080d05cc82',
    messagingSenderId: '100924810151',
    projectId: 'imgify-5fd0d',
    storageBucket: 'imgify-5fd0d.firebasestorage.app',
    iosBundleId: 'smoqdev.imgify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa2Su1HS9y6zHb-YL3KAyISkZFugyogRA',
    appId: '1:100924810151:ios:4ac3bf9b0108080d05cc82',
    messagingSenderId: '100924810151',
    projectId: 'imgify-5fd0d',
    storageBucket: 'imgify-5fd0d.firebasestorage.app',
    iosBundleId: 'smoqdev.imgify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIaTG2EvX5rMym8BVAzWr8Y43kbkAKuNo',
    appId: '1:100924810151:web:99159e9553933d3e05cc82',
    messagingSenderId: '100924810151',
    projectId: 'imgify-5fd0d',
    authDomain: 'imgify-5fd0d.firebaseapp.com',
    storageBucket: 'imgify-5fd0d.firebasestorage.app',
    measurementId: 'G-32DQC7WMJY',
  );
}
